### ISSUE TITLE
[BUG] ImportError: No module named 'configobj'

### ISSUE THREAD

**Issue by wzm2256** [bing-jian/gmmreg-python#2]
Hi, I wish to report a bug.

I followed the instruction in the readme file, but it does not work as expected.
I paste the trace back here.
```
Traceback (most recent call last):
  File "../demo.py", line 12, in <module>
    import plotting
  File "G:\CodeSet\PCR_Collection\gmmreg-python-master\plotting.py", line 5, in <module>
    from configobj import ConfigObj
ImportError: No module named 'configobj'
```

**Comment by bing-jian** [comment]
This configobj package ( https://pypi.org/project/configobj/ ) needs to be installed for running the demo program.
Now a list of required packages can be found in https://github.com/bing-jian/gmmreg-python/blob/master/requirements.txt

**Comment by wzm2256** [comment]
OK, I see.  Thanks!
